const express = require("express");
const router = express.Router();
const classController = require("../app/controllers/classController");

router.get("/", classController.index);
router.get("/information", classController.information);
router.get("/creatClass", classController.creatClass);
router.get("/arrangenClass", classController.arrangenClass);
router.get("/score", classController.score);
router.get("/scoreID", classController.scoreWithIdClass);
router.get("/scoreUpdate", classController.scoreUpdate);
router.put("/updatedScore", classController.updatedScore);
router.post("/addScore", classController.addScore);
router.get("/changeClass", classController.changeClass);
router.put("/changeClass", classController.putChangeClass);
router.get("/change", classController.getClassToChange);
router.get("/attend", classController.attend);
router.get("/attend-class", classController.attendClass);
router.post("/attend-student", classController.attendStudent);
router.post("/addClass", classController.addClass);
router.get("/updateClass", classController.formUpdateClass);
router.put("/updateClass", classController.updateClass);
router.put("/done", classController.doneClass);
router.get("/doneClassList", classController.doneClassList);
router.patch("/restore", classController.restoreClass);
router.post("/assign", classController.addTeacher);
router.get("/addStudentToClass", classController.addStudentToClass);
router.post("/addStudentToClass", classController.addStudent);
module.exports = router;
